### ISSUE TITLE
Death not by G-Force but speed

### ISSUE THREAD

**Issue by YourLocalPlonker** [studio-minus/ppg-bugs-and-requests#1279]
**Describe the bug**
I was playing with planes and noticed that pilots just died for no reason. The maneuvers I pulled were not very high-G. to simulate a high G-Force I set gravity to 200 m/s square (-200), froze the humans legs but nothing happened then I unfroze the legs and let the human accelerate towards the ground and he started dying despite being in a freefall and thus 0G. He should actually start dying when being idle because in that moment the human experienced 20.387 Gees constantly.

**Clearly describe how to reproduce the bug**
Accelerate a human a shit ton of speed

**Mod list**
N/A

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.24 preview
 - GPU: GTX 2070 ti 
 - CPU: Intel i9

Edit: This applies to all sorts of high speed movement also on the ground

**Comment by DindinYT37** [comment]
I guess zooi just wanted to save some time or G-Force is still from pre-remake?

**Comment by mestiez** [comment]
No this should not happen. G-force is calculated by measuring the change in body velocity (acceleration). The limb is damaged and the person is knocked out only if this acceleration is present for a while.

This means that G-force is calculated incorrectly, but not in a way that should cause issues. Setting the gravity to 20x the normal amount should do nothing until you drop a person from some height. They will experience 20 G the moment they start falling, and a minor amount of G-force during freefall (because gravity accelerates much faster than normal).

I'll make the calculation more accurate and see if it helps.
