### ISSUE TITLE
Pressing "C" with nothing selected clears your clipboard.

### ISSUE THREAD

**Issue by Uniconrzss** [studio-minus/ppg-bugs-and-requests#1504]
**Describe the bug**
If you have something in your clipboard and you press "C" while nothing is selected it will clear your clipboard

**Clearly describe how to reproduce the bug**
1. Have something copied.
2. Press C while not having anything selected.
3. Lose hours of time because you are too dumb to save and instead copy stuff :)

**Mod list**
No mods.

**System info (please complete the following information)**
 - Operating system: Win10
 - Game version: 1.24.6
 - GPU: GeForce GTX 1650
 - CPU: AMD Ryzen 5 3600

**Additional notes**

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaaaaaaaaaaaaaaaaaa MY SPACE SHIP IS GONE

**Comment by DindinYT37** [comment]
Doesn't happen to me, are you sure it wasn't because there was a part in what you copied that caused a serialization error? That usually causes the clipboard not to copy what was selected and just keep what was there before, and if you didn't copy anything before - it would obviously be gone. Though I still think this is just a part from a mod that caused serialization error since this doesn't happen to me, good luck to zooi to replicate this.

**Comment by Uniconrzss** [comment]
As written in the post i do not have any mods enabled and i was building with only vanilla parts at the time. Coppying and pasting my build worked but i cleared the map to clear the mess and instead of pressing v to paste i accidentally pressed c.

**Comment by DindinYT37** [comment]
> As written in the post i do not have any mods enabled and i was building with only vanilla parts at the time. Coppying and pasting my build worked but i cleared the map to clear the mess and instead of pressing v to paste i accidentally pressed c.

Then I don't know.

**Comment by mestiez** [comment]
I can't replicate this. Pressing C without anything selected does not clear the clipboard.
