### ISSUE TITLE
Please add a setting to remove gore

### ISSUE THREAD

**Issue by Sebbog1** [studio-minus/ppg-bugs-and-requests#1524]
**Feature description**
It would be a setting that would remove all gore sound effects and remove any visual gore.

**Feature purpose**
I have a friend that wants to play People Playground but they dont want any gore while playing.

**Additional context**
Just add a setting to remove gore.

**Comment by minorfam22** [comment]
yeah i recommend that cuz my mom would ground me if you dont

**Comment by DindinYT37** [comment]
Unnecessary work for a game that's 13+ (if not 16+).

**Comment by PossiblyRemember** [comment]
Honestly I don't have any problems with it but for anyone that does want to remove gore then that would be a nice option, and probably not too hard to code

**Comment by DindinYT37** [comment]
> Honestly I don't have any problems with it but for anyone that does want to remove gore then that would be a nice option, and probably not too hard to code

It was said several times to not estimate how hard something would be to implement, also there name a reason why that option should exist that would be worth the work.

**Comment by mestiez** [comment]
The implementation restricts the following:

- Liquid can't be red. Any red liquid will become orange.
- Procedural damage (stab wounds, bullet wounds, blunt damage wounds, burn marks, friction burns) is not rendered on humans. It's still visible on androids and gorses.
- Any blood particles & decals are also orange

I changed my mind on not wanting to implement this because I don't see why I should limit people from playing the game if their parents or caretakers are unusually strict.
