### ISSUE TITLE
make rebar sharp on both sides

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1860]
**Feature description**
for the concrete rebar being symetrical, it seems like it's only sharp on one side. i think it should be sharp on both sides

**Feature purpose**
consistency, it would make more sense

**Comment by DindinYT37** [comment]
They usually only have one sharp spot, the reason it looks like this is because it's one pixel wide.

References:
![image](https://user-images.githubusercontent.com/64973205/180666911-00e298e8-25f7-450d-90a6-05cf886df104.png)
![image](https://user-images.githubusercontent.com/64973205/180666918-68a99362-5cc8-41c6-9772-dfd3e52a9036.png)

**Comment by ATPGaming** [comment]
ill go ahead and close the issue then

**Comment by souphasapple** [comment]
i bet you could still get stabbed doesnt matter what side is sharp

**Comment by DindinYT37** [comment]
> i bet you could still get stabbed doesnt matter what side is sharp

You can get stabbed with everything that is even slightly hard if you try hard enough.
