### ISSUE TITLE
Advanced config options

### ISSUE THREAD

**Issue by michiel1106** [studio-minus/ppg-bugs-and-requests#1964]
**Feature description**
A new option where there are alot of options that can be turned on or off (maybe in some cases a slider or something) and the options would be something like:

Limbs explode when too much liquid in them true/false

humans die on impact <10m true/false

And maybe some mods can add more options like:

humans turn into androids when blood is replaced with oil          True/false

humans turn into superman when they get superman blood.        True/false

**Feature purpose**
I thought this may be fun because theres more modding options and when something is annoying you dont need to make/request a mod to change it. Like the limited camera zoom. Theres a mod for that but id rather just have an option

**Additional context**
Maybe some search bar

**Comment by DindinYT37** [comment]
* Limbs explode when too much liquid in them - already exists
* Humans die on impact <10m - quite impossible unless it's hard-coded which would make it feel wonky
* Humans turn into androids when blood is replace with oil - sounds like something from a mod
* Humans turn into superhuman when they get superhuman blood - I think you mean blood that was affected by the ultra strength syringe, but this sounds even more like something from a mod

Even if it is annoying that you need a mod for these kind of things, it's like that because they don't really belong in the vanilla game. Also, I don't know why'd you need a mod for the camera zoom as it's pretty much fine, though that's my opinion.

**Comment by michiel1106** [comment]
> * Limbs explode when too much liquid in them - already exists
> * Humans die on impact <10m - quite impossible unless it's hard-coded which would make it feel wonky
> * Humans turn into androids when blood is replace with oil - sounds like something from a mod
> * Humans turn into superhuman when they get superhuman blood - I think you mean blood that was affected by the ultra strength syringe, but this sounds even more like something from a mod
> 
> Even if it is annoying that you need a mod for these kind of things, it's like that because they don't really belong in the vanilla game. Also, I don't know why'd you need a mod for the camera zoom as it's pretty much fine, though that's my opinion.

Im not saying that those `arent` In the game, im saying that a feature to `toggle` All sorts of things in the game would be nice. Did you even read it?

**Comment by DindinYT37** [comment]
> Im not saying that those `arent` In the game, im saying that a feature to `toggle` All sorts of things in the game would be nice. Did you even read it?

I did read it, the problem here is that the only one that is already in the game was already once toggleable - I don't know why it isn't anymore (since I just checked) but it certainly was before. Also, how can you ask me if I even read it when you clearly ignored all the other arguments I presented you and went for one that isn't even really relevant...

**Comment by mestiez** [comment]
i think too many settings will make things too confusing and makes it even harder for contraptions to work across computers and games.
