### ISSUE TITLE
Burst Pistol

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2249]
**Feature description**
Add a Beretta 93R, a burst pistol chambered in 9mm

**Feature purpose**
To add both a machine pistol and burst weapon

**Additional context**
![image](https://user-images.githubusercontent.com/109692890/194741430-4652c8b8-a0c2-4bf9-96ea-8fd6bdd0f116.png)

**Comment by TeslaCoil9001** [comment]
1. Exact copy of #430
2. How is this different or useful
3. What is stopping you from making a burst weapon yourself

**Comment by ATPGaming** [comment]
> 1. Exact copy of [Berreta 93R #430](https://github.com/studio-minus/ppg-bugs-and-requests/issues/430)
> 2. How is this different or useful
> 3. What is stopping you from making a burst weapon yourself

OH MY GOD YOU'RE BECOMING DINDINYT37
(It's just a joke you're actually helpful DinDinYT37)

1. Ok I won't deny that
2. If you actually read the request it is a burst weapon
3. It's more convenient, why else would we have the table, chair, car, tree, etc. etc. that we can also make?

**Comment by TeslaCoil9001** [comment]
I'm just saying it's useless

**Comment by ATPGaming** [comment]
**It is a burst weapon, something we don't have in-game already**

We don't have a burst weapon in-game yet, and that's why it's new and intresting

**Comment by ATPGaming** [comment]
If this turns into another long and stupid argument we might both get banned from this respiratory

**Comment by TeslaCoil9001** [comment]
And I'm just saying it's not unique enough to be added, just make a burst weapon yourself

**Comment by ATPGaming** [comment]
Stop, ok? I'm tired of these arguments. There's no point in arguing when it just continues to go back and forth discussing the same issues and not progressing. It makes us look immature and foolish. I never want to argue with anyone and if we keep doing it, we'll not only be hurting ourselves, but we'll also be hurting everyone else who wants to see the issue. Imagine scrolling down to an issue, and BOOM, an entire encyclopedia of conclusion hopping and one-sided points. The only thing arguing will ever end in is someone upset, and someone who makes themselves look ignorant. Just quit arguing, okay? I never want to make anyone upset but you're making me feel like I committed a crime against humanity.

**Comment by DindinYT37** [comment]
> > 1. Exact copy of [Berreta 93R #430](https://github.com/studio-minus/ppg-bugs-and-requests/issues/430)
> > 2. How is this different or useful
> > 3. What is stopping you from making a burst weapon yourself
> 
> OH MY GOD YOU'RE BECOMING DINDINYT37 (It's just a joke you're actually helpful DinDinYT37)

At least spell my name right...

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #430 (Literal duplicate)
* #1832 (Also made by @ATPGaming, closed because it was possible to make in Vanilla and mods already added it)
* #2124

_Also, in my opinion, you're both acting extremely childish and ignorant here. Because of which you're both unable to come to a compromise – even though I could understand if it was just one person acting that way, neither of you even thought about that for a second._

To clear up all the three points that were presented earlier:
1. Literal duplicate, as said.
2. As mentioned in #1832 and now here, a burst weapon can be made in vanilla and was also already added by mods.
3. Comparing an everyday life object that always comes in handy to a gun of a specific type is completely idiotic. Not to mention that we also **did** have to make trees ourselves (usually with mods) until recent updates.


I know this comment may come off as rude, but it's quite honestly just upsetting that you both keep getting into arguments not because of one of you, but because you're both acting that way.

**Comment by ATPGaming** [comment]
> I know this comment may come off as rude, but it's quite honestly just upsetting that you both keep getting into arguments not because of one of you, but because you're both acting that way.

I never want to argue, and the last thing I want to do is make someone upset or angry. I'm gonna try my best to never let this happen again, and all of these arguments are probably my fault anyways. I just never do anything right. I don't want to let drama happen, it's heartbreaking to see anyone in an altercation.

I'll close the issue now.

**Comment by TeslaCoil9001** [comment]
> > I know this comment may come off as rude, but it's quite honestly just upsetting that you both keep getting into arguments not because of one of you, but because you're both acting that way.
> 
> I never want to argue, and the last thing I want to do is make someone upset or angry. I'm gonna try my best to never let this happen again, and all of these arguments are probably my fault anyways. I just never do anything right. I don't want to let drama happen, it's heartbreaking to see anyone in an altercation.
> 
> I'll close the issue now.

Ok I kind of feel like a dick now. I don't know what to say besides I'm bad at _not_ arguing. It doesn't mean I like arguing though.
