### ISSUE TITLE
add a p90

### ISSUE THREAD

**Issue by HitgubWasTaken** [studio-minus/ppg-bugs-and-requests#2332]
add p90, it would have an extremely fast fire rate with a lot of penetration and damage very slightly lower than the assault rifle

we need a haha BRRRRR submachine gun, the fastest firing weapon we have is minigun but it doesn't give the feel of the 5.7mm bullet hose we so love

it would probably be called personal defense weapon or 5.7 submachine gun

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #1358 
* #1793 
* #2213 

Also, please use the template.

**Comment by TeslaCoil9001** [comment]
> Duplicate of or Related to:
> 
> * [P90 #1358](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1358)
> * [Armor-piercing AR #1793](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1793)
> * [MAC-11 #2213](https://github.com/studio-minus/ppg-bugs-and-requests/issues/2213)
> 
> Also, please use the template.

They did. They did use the template. The point of the template is to keep the feature request organized, even if they don't use the headers it still keeps the feature request neat. You still get the idea that there is a feature request, feature purpose, and additional context. I'm only saying this because I think it is unnecessary if to point it out as not using the template if they keep the structure but remove the headers, but really it isn't very clear in the template that you have to use the headers, or use it at all which is why I wish there were instructions for it which would prevent people from either not using it or writing single sentences. You still get the idea of the feature in a neat way that provides all the information, and I'm pretty sure you can infer what the information is using context without the headers. All I'm saying is I think it's pointless to point out they didn't use the headers if they still used the structure and you can still tell the information.

Not to mention this was completely pointless saying this after they re-did their issue to use the headers.

**Comment by HitgubWasTaken** [comment]
> Duplicate of or Related to:
> 
> * [P90 #1358](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1358)
> * [Armor-piercing AR #1793](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1793)
> * [MAC-11 #2213](https://github.com/studio-minus/ppg-bugs-and-requests/issues/2213)
> 
> Also, please use the template.

do I close it again or something what do you want from me I already know to use the template now

**Comment by DindinYT37** [comment]
> > Duplicate of or Related to:
> > 
> > * [P90 #1358](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1358)
> > * [Armor-piercing AR #1793](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1793)
> > * [MAC-11 #2213](https://github.com/studio-minus/ppg-bugs-and-requests/issues/2213)
> > 
> > Also, please use the template.
> 
> do I close it again or something what do you want from me I already know to use the template now

I recommend closing #2333 and just editing this issue.

**Comment by DindinYT37** [comment]
> > Duplicate of or Related to:
> > 
> > * [P90 #1358](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1358)
> > * [Armor-piercing AR #1793](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1793)
> > * [MAC-11 #2213](https://github.com/studio-minus/ppg-bugs-and-requests/issues/2213)
> > 
> > Also, please use the template.
> 
> They did. They did use the template. The point of the template is to keep the feature request organized, even if they don't use the headers it still keeps the feature request neat. You still get the idea that there is a feature request, feature purpose, and additional context. I'm only saying this because I think it is unnecessary if to point it out as not using the template if they keep the structure but remove the headers, but really it isn't very clear in the template that you have to use the headers, or use it at all which is why I wish there were instructions for it which would prevent people from either not using it or writing single sentences. You still get the idea of the feature in a neat way that provides all the information, and I'm pretty sure you can infer what the information is using context without the headers. All I'm saying is I think it's pointless to point out they didn't use the headers if they still used the structure and you can still tell the information.
> 
> Not to mention this was completely pointless saying this after they re-did their issue to use the headers.

Stopped reading after around 3 sentences since I know you're going to talk nonsense again. Let me clear this up: The point of the template is to keep the issues organized, yes – but the reason the template exists in the first place is to use it, no matter what reason you present; as long as the template exists, you're supposed to use it.

Not to mention that, I told you before that nobody that didn't already read a lot of issues would know that this would be using the template without the headers. It's like taking an exam, but you don't get the questions because "you learned them already, so you should know".

**Comment by TeslaCoil9001** [comment]
> > > Duplicate of or Related to:
> > > 
> > > * [P90 #1358](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1358)
> > > * [Armor-piercing AR #1793](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1793)
> > > * [MAC-11 #2213](https://github.com/studio-minus/ppg-bugs-and-requests/issues/2213)
> > > 
> > > Also, please use the template.
> > 
> > 
> > They did. They did use the template. The point of the template is to keep the feature request organized, even if they don't use the headers it still keeps the feature request neat. You still get the idea that there is a feature request, feature purpose, and additional context. I'm only saying this because I think it is unnecessary if to point it out as not using the template if they keep the structure but remove the headers, but really it isn't very clear in the template that you have to use the headers, or use it at all which is why I wish there were instructions for it which would prevent people from either not using it or writing single sentences. You still get the idea of the feature in a neat way that provides all the information, and I'm pretty sure you can infer what the information is using context without the headers. All I'm saying is I think it's pointless to point out they didn't use the headers if they still used the structure and you can still tell the information.
> > Not to mention this was completely pointless saying this after they re-did their issue to use the headers.
> 
> Stopped reading after around 3 sentences since I know you're going to talk nonsense again. Let me clear this up: The point of the template is to keep the issues organized, yes – but the reason the template exists in the first place is to use it, no matter what reason you present. As long as the template exists, you're supposed to use it.
> 
> Not to mention that, I told you before that nobody that didn't already read a lot of issues would know that an issue would be using the template without the headers. It's like taking an exam, but you don't get the questions because "you learned them already, so you should know".

Yes because I only talk nonsense

**Comment by TeslaCoil9001** [comment]
That's not even sarcasm
