### ISSUE TITLE
Procedural fragments disappearing after every limb is crushed

### ISSUE THREAD

**Issue by Was1fy** [studio-minus/ppg-bugs-and-requests#2640]
### Describe the bug

Every flesh and bone fragment that belongs to one human disappear when every limb of that human is crushed. 
I'm not sure if this is a bug but it gets annoying sometimes.

### Clearly describe how to reproduce the bug

1- Spawn a human
2- Spawn something heavy (1000 kg weight in this case)
3- Crush every part of the human's body
4- After the last part is crushed every bone and flesh fragment will disappear

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10368393/exported.game.debug.info.md)

### Game version

1.26.2

### Operating System

Windows 10

### Additional notes

https://user-images.githubusercontent.com/72949489/211195776-6a5d1b9e-2c39-4002-ab80-f5b5f1d22dd9.mp4

**Comment by Drogo-man** [comment]
I think this is a combination of #193 and #2613 creating a new bug

**Comment by Was1fy** [comment]
> I think this is a combination of #193 and #2613 creating a new bug

I agree. Don't know if there's any possible way to fix this.

**Comment by Was1fy** [comment]
I don't know programming but maybe add an option in the menu to disable deleting humans on full limb crush if there's no better way to fix this ?

**Comment by DindinYT37** [comment]
You could simply check if the human was deleted by the user or by being crushed. If it was deleted by the user, remove all procedural fragments with it – if it was deleted by crushing, keep the fragments(?). The idea might work, but I am unsure about the execution.

**Comment by bibbybabby** [comment]
I think that the gibs are just children of the human entity. When one of the parts are destroyed a group of gibs spawn that is parented to the human group, if the entire group is destroyed it is removed, removing the children in the process.

A solution might be making them a part of the group instead of children, so when the human is destroyed the group is not removed because there are members (gibs) in it.

I am not saying this as fact because I do not have the PPG source code and the Unity project file

**Comment by mestiez** [comment]
They are not children. They're just being removed when the root object is removed. When all parts of an object are disintegrated (crushed), the root object is also deleted.

A solution to this would be to register the gibs as "part of the object", so that the root is only deleted when the fragments are also deleted.

**Comment by mestiez** [comment]
fixed :)
