### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by Popcornboy333** [studio-minus/ppg-bugs-and-requests#2944]
### Describe the bug

Changing The Temperature On The Map Doesn't Change Anything, And The Humans Temperatures Only Drop To Negatives After You Kill Them, And Once You Revive Them Their Temperatures Rise Back to 35 C
Also If You Keep Them In The Cold For Too Long Their Temperature Stays The Same But Their Feet And Hands Rot

### Clearly describe how to reproduce the bug

Just Spawn A Human And Set The Temperature To -100 C And Inspect The Humans Body Temperature, They Gitter A Bit But Their Temperature Doesn't Drop

### Mod list

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/f50957a5-7f77-4294-abda-c5b26c1a5e54)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/9c8c7bbd-b0e8-458c-9efd-c6585285195e)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/15ceaadd-1ca7-440f-8bc9-ff7ae45600e7)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/60f49735-8793-4e65-861f-8d3a47e15f8f)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/dd55aecf-5fea-4503-8d17-104dc8c5a252)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/78cffda6-beb2-4459-89e3-5f6954276d49)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/46a762b7-548a-4995-8ff5-a9f9147e68a8)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/5163fdaa-202c-453f-a10b-95fe843dd28e)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/027f850f-1d51-4f7d-8080-6f0a5045641e)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/c1734b51-ef3d-4990-b453-96af972e22cc)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/206cb3e6-8c20-4e05-a9b1-8e3128ef8daa)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/dcb3e9b6-5526-489b-be4b-1e0069817ca3)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/1c7abe6e-14c1-4d1a-b459-502b5e4e633e)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/6ad317b3-f702-49b5-a22c-da16ba313420)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/3ad897f9-c943-4043-b2f7-05118c1a6351)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/4cc1e9af-b6bc-49da-97b7-b65a4b3fee48)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/98224577/1259f92e-7286-4c37-beeb-1cfa55b05bed)
(I disables all of the mods to make sure it wasn't one of them causing the bug)

### Game version

1.26

### Operating System

Windows 11

**Comment by myron-obsolete-account** [comment]
yo why your mod list so long

**Comment by Popcornboy333** [comment]
theyre more fun that way, plus like 1/3 of them I just needed them for other mods or saved contraptions

**Comment by ras09191** [comment]
those are a lot of mods lol

**Comment by u0068** [comment]
This is not a bug:
The inspect menu shows the humans internal temperature, which they keep close to 37 to keep themselves alive.
Once theyre dead they cant do that anymore so internal temp drops to the same as external temp.
Also, if ambient temperature transfer is disabled, they can only lose heat by touching other objects and since theyre probably only touching the floor they are losing heat very slowly which is why their temperature is more or less constant.
If you want them to change temperature quickly just enable ambient temp transfer becuase then they can lose/gain heat through the air as well.
If you want to see their external temperature instead of internal, press the T key to turn on thermal vision and mouse over the human. 
Hands and feet are rotting because they get frostbite due to the low temperatures.
