### ISSUE TITLE
temperature bug

### ISSUE THREAD

**Issue by Theklapek** [studio-minus/ppg-bugs-and-requests#354]
**Describe the bug**
When you use set temperature feature and set it to a very large positive number like 51286729167192867910 it shows that object temperature is -2147483648

**Clearly describe how to reproduce the bug**
Spawn random object in which you can check the temperature ( for example human)
Set temperature of it to very large positive number like 51286729167192867910
Inspect it
It shows that object temperature is -2147483648

**Mod list**
Death note by Maxe - Active
Black Hole Tool by davidco7777 - Active 
Quick Right Click Options by Pump3d - Inactive
Animated Weapons+ by Mishanya - Active
Human Tiers by Alibarda - Active
Active Humans by quaq - Active

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22 beta 3 (64 bit)
 - GPU: NVIDIA GeForce GTX 1650 SUPER
 - CPU: Intel Core i5-9400F 2.90GHz

**Additional notes**

**Comment by TamasB14** [comment]
I think it's because of the normal Computing. Numbers a basically used as binary. For example the number 11 in binary is 1011 etc. When you make such abnormally high numbers it will take up alot of binary space for example the one you wrote is: **101100011110111111000100000111001011100110001100100100010001000110** which might cause them to go into negative. Atleast that's what another community told me in another game when I hit like... 21234123414 amount of money and it just reseted to 0.

**Comment by mestiez** [comment]
yes this is an overflow issue. clamping should fix it
