### ISSUE TITLE
Unrotting limbs

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#364]
**Feature description**
Alive limbs should unrot themselves since well their alive

**Feature purpose**
As a way to unrot limbs without using the mending syringe 

**Additional context**
None.

**Comment by TamasB14** [comment]
Thing is, in real life once your bodypart is rotten, it won't rever the change as all your blood vessels got damaged and old it cannot reproduce the parts needed to revive that bodypart. That's why these bodyparts get amputated. Most common "rotting" is the frostbite, which is similiar to burning. You can see how these limbs get a frostbite and cannot regenerate themselves.

**Comment by fhgb54643689** [comment]
> Thing is, in real life once your bodypart is rotten, it won't revert the change as all your blood vessels got damaged and old, so it cannot reproduce the parts needed to revive that bodypart. That's why these bodyparts get amputated. Most common "rotting" is the frostbite, which is similiar to burning. You can see how these limbs get a frostbite and cannot regenerate themselves.

ah interesting i did not know that
