### ISSUE TITLE
Metal Detector

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#408]
**Feature description**
A machine that detects metal items. (sometimes in the ground)

**Feature purpose**
For the sand map suggestion as I said there should be guns and misc metal items in the ground.

![nokta-makro-simplex-metal-detector-1](https://user-images.githubusercontent.com/55041380/139777333-914e8c5b-5db7-448d-a6d0-5931a2f50d79.jpg)

**Comment by atwal6400** [comment]
> you can literally make one with a rod and a metal detector

I agree but the design would be better for a vanilla standpoint.

**Comment by alikeobservant** [comment]
> > you can literally make one with a rod and a metal detector
> 
> I agree but the design would be better for a vanilla standpoint.

no dude the whole point of the game is to inspire creativity e.g minecraft removed furniture because they wanted the community to get creative and make things, instead of just having it there. for example, an elevator. if that were to be added, no elevator mods were to exist. if destructable tanks were vanilla, there would be no good tank mods and so on.

**Comment by mestiez** [comment]
There is already a metal detector.
