### ISSUE TITLE
question

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#438]
why is flipping heck not in the game itself? it's such a simple thing yet so key to doing some things on ppg.

**Comment by UniDuki** [comment]
If you were to simply read the description of the mod:

### Why this is not in the base game
It is very slow for a simple "flip" action. The game was never designed with flipping-after-spawning in mind. The way this addon works is that it serialises the selection, and deserialises it flipped around. Almost identical to saving something and then spawning it flipped. It's slow and doesn't even preserve the selection fully. The only true way to make flipping-after-spawning work correctly is to rewrite the foundations of the game and possibly rewrite hundreds of scripts specific to items.

So instead of doing that and likely breaking 99% of all contraptions you have saved, I made this mod. Making mods comes with the privileges of it being OK to release barely working code. It's just a mod, after all.

**Comment by bluewoods64** [comment]
> If you were to simply read the description of the mod:
> 
> ### Why this is not in the base game
> It is very slow for a simple "flip" action. The game was never designed with flipping-after-spawning in mind. The way this addon works is that it serialises the selection, and deserialises it flipped around. Almost identical to saving something and then spawning it flipped. It's slow and doesn't even preserve the selection fully. The only true way to make flipping-after-spawning work correctly is to rewrite the foundations of the game and possibly rewrite hundreds of scripts specific to items.
> 
> So instead of doing that and likely breaking 99% of all contraptions you have saved, I made this mod. Making mods comes with the privileges of it being OK to release barely working code. It's just a mod, after all.

sorry i dont read every small print writing of the game. i dont understand why you get so mad and thumbs down like 90% of the requests on this page. youre honestly so annoying.
