### ISSUE TITLE
Fast moving objects displaying incorrectly (hear me out)

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#543]
**Description**
So we all now that when you're in slow motion and there is something moving extremely fast, it becomes insanely hard to grab it.

**My fix Idea**
Recently I've found out, that when toggling thermal vision (and it's hot/cold or a living being) you can clearly see where you have to grab.
<img src="https://user-images.githubusercontent.com/64973205/143092230-567fadde-7862-4902-b8d4-dd45a7cdeb04.png" width=200 />

Which basically means for me, that there is indeed a possible fix. I am unsure if this is an intended feature or a bug because of the interpolation.
I have thought of multiple solutions:
A) Make the interpolation toggleable (Settings)
B) Make the interpolation faster the faster the velocity so it's more accurate
C) Make it show the right position (in outline) when in detail view

**Comment by mestiez** [comment]
> Make the interpolation toggleable (Settings)

This is not viable because physics updates at 50Hz. This is almost always below the game's framerate and will cause the entire game to look like it's running at 50 frames per second.

> Make the interpolation faster the faster the velocity so it's more accurate

This is not possible.
<details>
<summary>Why?</summary>

![image](https://user-images.githubusercontent.com/32131519/143094839-bda4a9fe-0b6a-464e-b5bc-fdd30221e366.png)

</details>

> Make it show the right position (in outline) when in detail view

I suspect this would cause major confusion consideirng thermal vision had people confused too. I could be completely wrong though.

**Comment by mestiez** [comment]
Thermal vision shows the actual position because it tests for physical objects in the world, it doesn't care about the visual representation.
