### ISSUE TITLE
Many contraptions are now corrupted. And those that work have become strange

### ISSUE THREAD

**Issue by AlexCodeMan** [studio-minus/ppg-bugs-and-requests#841]
Complex buildings shake a lot and don’t work (or are even listed as corrupted. Although if you go to the stable version (the last one), then everything is fine.

I noticed this error when I downloaded the Monarch Titan (there are various buildings from Titanfall in the Steam Workshop). They will either be listed as corrupted or they will constantly rattle (seriously, they are downright unstable now)

I have a lot of mods, I would go crazy listing them. Again, they are not the problem. Something about an update. Everything was ok in the previous version.

 - Operating system: Windows 10
 - Game version:
 - GPU:2060rtx
 - CPU:i7-8700

Zooi, please correct the errors. I have many buildings flew to one place ...

**Comment by mestiez** [comment]
> Again, they are not the problem. 

Please don't assume you know whats going on here. Just give the requested information and let me figure it out

**Comment by mestiez** [comment]
Can you send a contraption (vanilla) that used to work but no longer does?

**Comment by AlexCodeMan** [comment]
This is where things get really weird. Twitching and behaving abnormally. I checked on the previous version everything is in order.
https://steamcommunity.com/sharedfiles/filedetails/?id=2732060675
____________________
These have become corrupted:
https://steamcommunity.com/sharedfiles/filedetails/?id=2694742745
https://steamcommunity.com/sharedfiles/filedetails/?id=2688813518
https://steamcommunity.com/sharedfiles/filedetails/?id=2680300818
and others, not only from this author

**Comment by Afavertov** [comment]
Every save with 30mm cannon corrupted

**Comment by WWWOWWWPL** [comment]
newer saves with 120mm cannons also seem to get corrupted, just tested it

**Comment by AlexCodeMan** [comment]
Hey Zooi! So what about the error? It turned out that all the buildings with **120 and 30 mm** guns break down. And some contraptions "**tremble**", it's hard to explain.

**Comment by mestiez** [comment]
1.23 replaces some parts of the serialiser (absolutely necessary). The cause of the problem is the serialiser (seemingly) using a different implementation of `UTF8Encoding` than it previously did. Apparently this causes issues with numbers in the `SpawnableAsset `name that I haven't found a fix for. 

 I have tried:
 - Changing the string formatter to a custom implementation that tries UT8 and fallsback to ASCII. This somehow caused an even more obscure error.
 - Copying the UTF8Encoding used by the previous serialiser and adding it to the Unity project. This wouldn't compile because the implementation uses some weird `internal `shit (fuck access modifiers).

**It's not viable to revert back to the old serialiser library file. Aside from the fact that they're supposedly the exact same version, the old one required a bunch of files that conflict with Dear Imgui. I hate working in Unity because this would work just fine outside of it.**

If anyone knows what to do here, don't hesitate to contact me.

**Comment by AlexCodeMan** [comment]
I myself am a junior developer. Maybe you should check forums like **stackoverflow**. Because the problem is really serious.

**Comment by mestiez** [comment]
stackoverflow is usually useless when it comes to actual problems unfortunately

**Comment by mestiez** [comment]
> newer saves with 120mm cannons also seem to get corrupted, just tested it

Newer saves work perfectly fine on my end

**Comment by mestiez** [comment]
I give up for real lmao

**Comment by DindinYT37** [comment]
Classic moment in the life of a programmer.
